- branches:
    only:
    - master
  build_script:
  - build.cmd install
  environment:
    DNX_FEED: https://www.nuget.org/api/v2
    BUILDCMD_RELEASE: beta6
    NUGET_PUBLISH_FEED: https://nuget.org/

- branches:
    only:
    - dev
  init:
  - ps: Get-ChildItem "env:"
  on_finish: 
  version: 1.0.{build}
  environment:
    BUILDCMD_RELEASE: beta6
    DNX_FEED: https://www.nuget.org/api/v2
    access_token:
      secure: eky2kG/ZhEG+YFwZcE5ELS8ZYN/HhbNszojPhV0xO54OjIVBYyctb6oS0yAm5eZ3
  cache:
  - sample\usermanagement\node_modules
  - C:\Users\appveyor\.dnx\packages
  - C:\Users\appveyor\AppData\Roaming\npm
  build_script:
  - echo start build
  - build.cmd  verify
  - echo end build
  deploy: off
  on_success:
  - echo build success goto deploy
  - git config --global credential.helper store
  - git config --global user.email thom@kiesewetter.nl
  - git config --global push.default simple
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://eb18825bac19311c122d2803008210215f60ee5f:x-oauth-basic@github.com`n"
  - git clean -f
  - git checkout master
  - git merge dev
  - git push
