- branches:
    only:
    - master
  build_script:
  - build.cmd install
  environment:
    DNX_FEED: https://www.nuget.org/api/v2
    BUILDCMD_RELEASE: beta7
    NUGET_PUBLISH_FEED: https://nuget.org/
    access_token:
      secure: 2yEFAtz1ISCey+VU+BGk/bmp4vV97rKpYrte9g5TqDDkXyFRz/flkD+Jzj+QWVjP
  deploy: off
  test: off

- branches:
    only:
    - dev
  init:
  - ps: Get-ChildItem "env:"
  on_finish: 
  version: 1.0.{build}
  environment:
    BUILDCMD_RELEASE: beta7
    DNX_FEED: https://www.nuget.org/api/v2
    access_token:
      secure: 2yEFAtz1ISCey+VU+BGk/bmp4vV97rKpYrte9g5TqDDkXyFRz/flkD+Jzj+QWVjP
  cache:
  - sample\usermanagement\node_modules
  - C:\Users\appveyor\.dnx\packages
  - C:\Users\appveyor\AppData\Roaming\npm
  build_script:
  - echo start build
  - build.cmd  verify
  - echo end build
  deploy: off
  test: off
  on_success:
  - echo build success goto deploy
  - git config --global credential.helper store
  - git config --global user.email thom@kiesewetter.nl
  - git config --global user.name appveyor
  - git config --global push.default simple
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git checkout -- *
  - git checkout master
  - git merge dev
  - git push
