#init:
#  - git config --global core.autocrlf true
#build_script:
#   - echo hallo
#   # - build.cmd --quiet --parallel
#clone_depth: 1
#test: off
#deploy: on
# environment:
  # deploy_project: simple-web
  # deploy_version: ''            # download artifacts from latest build if no version specified
  # deploy_artifact: ''           # download all artifacts if empty
  
  # deployment specific settings
  # we are going to deploy using Web Deploy, so...
  # webdeploy_package: '%appveyor_build_folder%\MyWebApp.zip'
  # webdeploy_server: mvcjquerydatatables.scm.azurewebsites.net:443
  # webdeploy_site: MVCJqueryDatatables
  # webdeploy_username: $MVCJqueryDatatables
  # webdeploy_password:zhuBYXp213NQJK3KkhjtmpdMtSorBce9bkEESvzwFcxHfKueKMW96vyXxTtf


# download project artifacts
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: Get-ChildItem "env:"
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# here is your own custom deployment code
# deploy_script:
#   - '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package="%webdeploy_package%" -dest:auto,ComputerName="%webdeploy_server%",UserName="%webdeploy_username%",Password="%webdeploy_password%",AuthType="Basic" -setParam:"IIS Web Application Name"="%webdeploy_site%" -allowUntrusted'
version: 1.0.{build}
environment:
  APIKEY: efb6f507-0d0c-4628-9e69-7fb38810615e
  NUGET_PUBLISH_FEED: https://nuget.org/
  BUILDCMD_RELEASE: beta6
  DNX_FEED: https://www.nuget.org/api/v2
  source_IisApp: PublishTemp\wwwroot
  dest_IisApp: MVCJqueryDatatables
  dest_ComputerName: https://mvcjquerydatatables.scm.azurewebsites.net/msdeploy.axd
  dest_UserName: $MVCJqueryDatatables
  dest_Password: zhuBYXp213NQJK3KkhjtmpdMtSorBce9bkEESvzwFcxHfKueKMW96vyXxTtf
  access_token: 
     secure: eky2kG/ZhEG+YFwZcE5ELS8ZYN/HhbNszojPhV0xO54OjIVBYyctb6oS0yAm5eZ3
cache:
- bower_components
- node_modules
- C:\Users\appveyor\AppData\Roaming\npm
build_script:
- echo start build
- build.cmd  install
- echo end build
test_script:
- echo test
artifacts:
- path: '**\*.nukpg'
  type: WebDeployPackage
deploy: off
on_failure:
- echo build failed
on_success:
- echo build success goto deploy
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://eb18825bac19311c122d2803008210215f60ee5f:x-oauth-basic@github.com`n"
- git commit -m build
- git push
